# Generated by Django 4.2 on 2023-08-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgTypes', models.CharField(max_length=100, null=True)),
                ('new_img', models.CharField(default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgName', models.CharField(max_length=1000, null=True)),
                ('new_imgs', models.CharField(default=1, max_length=2, null=True)),
                ('ID_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Img_Api.imagetype')),
            ],
        ),
    ]
