# Generated by Django 4.2 on 2023-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Imae',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
