# Generated by Django 4.2 on 2023-09-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0002_images_imae'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
