# Generated by Django 4.2 on 2023-09-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0008_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
