# Generated by Django 4.2 on 2023-09-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_Api', '0011_imgs_delete_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imgs',
        ),
    ]
